<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'id_role' => 2,
                'name' => 'Michael Anderson',
                'username' => 'patrickfischer',
                'email' => 'michelleaurelia1544@gmail.com',
                'email_verified_at' => null,
                'password' => bcrypt('password1'),
                'remember_token' => Str::random(10),
                'created_at' =>  now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'id_role' => 2,
                'name' => 'Kaitlyn Pham',
                'username' => 'lvasquez',
                'email' => 'levinedavid@schultz.info',
                'email_verified_at' => '2024-04-13 03:43:34',
                'password' => bcrypt(')SrhCIkN3d'),
                'remember_token' => Str::random(10),
                'created_at' =>  now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'id_role' => 3,
                'name' => 'Daniel Norris',
                'username' => 'staylor',
                'email' => 'jeannegomez@gmail.com',
                'email_verified_at' => '2024-05-23 02:52:02',
                'password' => bcrypt('(1T4kX3X@e'),
                'remember_token' => Str::random(10),
                'created_at' =>  now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'id_role' => 3,
                'name' => 'Joseph Torres',
                'username' => 'ywoodard',
                'email' => 'ambercrawford@gmail.com',
                'email_verified_at' => '2024-01-02 09:11:52',
                'password' => bcrypt('@eLRUcnQ05'),
                'remember_token' => Str::random(10),
                'created_at' =>  now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'id_role' => 2,
                'name' => 'Joseph Davis',
                'username' => 'silvanicholas',
                'email' => 'wallacenicholas@hotmail.com',
                'email_verified_at' => '2024-01-12 21:05:39',
                'password' => bcrypt('&J0MBb3kB7'),
                'remember_token' => Str::random(10),
                'created_at' =>  now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'id_role' => 1,
                'name' => 'Alex Brown',
                'username' => 'alexbrown',
                'email' => 'kasir@gmail.com',
                'email_verified_at' => '2024-02-20 14:12:45',
                'password' => bcrypt('kasir123'),
                'remember_token' => Str::random(10),
                'created_at' =>  now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'id_role' => 3,
                'name' => 'Emily Watson',
                'username' => 'emwatson',
                'email' => 'emwatson@gmail.com',
                'email_verified_at' => null,
                'password' => bcrypt('Watson*2024'),
                'remember_token' => Str::random(10),
                'created_at' =>  now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'id_role' => 1,
                'name' => 'Sophia Lee',
                'username' => 'slee',
                'email' => 'slee@gmail.com',
                'email_verified_at' => '2024-03-18 07:15:00',
                'password' => bcrypt('Sophia123'),
                'remember_token' => Str::random(10),
                'created_at' =>  now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'id_role' => 2,
                'name' => 'James Brown',
                'username' => 'jamesbrown',
                'email' => 'jamesbrown@example.com',
                'email_verified_at' => '2024-05-07 08:45:00',
                'password' => bcrypt('James!2024'),
                'remember_token' => Str::random(10),
                'created_at' =>  now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'id_role' => 3,
                'name' => 'Chloe Green',
                'username' => 'chloegreen',
                'email' => 'chloegreen@example.com',
                'email_verified_at' => null,
                'password' => bcrypt('Chloe$2024'),
                'remember_token' => Str::random(10),
                'created_at' =>  now(),
                'updated_at' => null,
                'deleted_at' => null,
            ]
        ]);
    }
}
